spring:
  config:
    activate:
      on-profile: local
    import: optional:classpath:application-local-secret.yml

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ticketing}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update

app:
  sample-data:
    events:
      enabled: true
    admin:
      enabled: true
      email: ${APP_SAMPLE_ADMIN_EMAIL:admin@example.com}
      password: ${APP_SAMPLE_ADMIN_PASSWORD:admin1234}
